name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform fmt / validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: terraform fmt
        run: terraform fmt -check -recursive

      - name: terraform init
        working-directory: terraform
        run: terraform init -backend=false

      - name: terraform validate
        working-directory: terraform
        run: terraform validate

  security-scan:
    name: Checkov security scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform
          framework: terraform
          quiet: true
          soft_fail: false

  python-tests:
    name: pytest (moto)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest -v
